//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MooShark2
{
    using System;
    using System.Collections.Generic;
    
    public partial class clarificationAnswer
    {
        public int id { get; set; }
        public int authorId { get; set; }
        public string message { get; set; }
        public Nullable<System.DateTime> posted { get; set; }
        public int clarificationId { get; set; }
    
        public virtual account account { get; set; }
        public virtual clarification clarification { get; set; }
    }
}
