//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MooShark2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VLN2_2016_H32Entities : DbContext
    {
        public VLN2_2016_H32Entities()
            : base("name=VLN2_2016_H32Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<account> account { get; set; }
        public virtual DbSet<assignment> assignment { get; set; }
        public virtual DbSet<clarification> clarification { get; set; }
        public virtual DbSet<clarificationAnswer> clarificationAnswer { get; set; }
        public virtual DbSet<clarifications> clarifications { get; set; }
        public virtual DbSet<courses> courses { get; set; }
        public virtual DbSet<grades> grades { get; set; }
        public virtual DbSet<groupMembers> groupMembers { get; set; }
        public virtual DbSet<problem> problem { get; set; }
        public virtual DbSet<problems> problems { get; set; }
        public virtual DbSet<roles> roles { get; set; }
        public virtual DbSet<students> students { get; set; }
        public virtual DbSet<submission> submission { get; set; }
        public virtual DbSet<submissions> submissions { get; set; }
        public virtual DbSet<teachers> teachers { get; set; }
        public virtual DbSet<team> team { get; set; }
        public virtual DbSet<teams> teams { get; set; }
        public virtual DbSet<testcase> testcase { get; set; }
        public virtual DbSet<testcaseOutput> testcaseOutput { get; set; }
        public virtual DbSet<testcases> testcases { get; set; }
    }
}
